[package]
name = "huffman-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.3"
bitvec = "1.0.1"
priority-queue = "1.3.2"
rayon = "1.7.0"
trees = "0.4.2"

[profile.release]
opt-level = 3
